# Generated by Django 5.2.3 on 2025-07-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_userstock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stocks',
            new_name='Stock',
        ),
    ]
