# Generated by Django 5.2.3 on 2025-07-10 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_rename_stocks_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Stocks',
        ),
    ]
